### ISSUE TITLE
Console.bark errrors

### ISSUE THREAD

**Issue by JosiasAurel** [twanmulder/console.bark#1]
Hello. When I install the package and try using it. I keep on getting errors like it's not a function or it missing initializer.

Even when I require and make an instance 
```shell
const bark = require('console.bark')()
```
Errors still arise. Please help or fix that

**Comment by twanmulder** [comment]
Great question! For the usage of "console.bark", you only have to use the require statement.

```javascript
require('console.bark');
```

After this, it can be used inside your JS file by calling "console.bark"

```javascript
require('console.bark');

console.bark('Bark!');
```

There's no need to assign it to a new variable.
If you still run into problems, please let me know!

**Comment by JosiasAurel** [comment]
Thanks it worked
